//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImapBayes.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImapBayes.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE tblAccounts (
        ///	id INT IDENTITY PRIMARY KEY,
        ///	strName NVARCHAR(100) NOT NULL,
        ///	strHost VARCHAR(100) NOT NULL,
        ///	strUser VARCHAR(100) NOT NULL,
        ///	strPass VARCHAR(100) NOT NULL,
        ///	nPort INT NOT NULL,
        ///	fUseSsl BIT NOT NULL,
        ///	fActive BIT NOT NULL,
        ///	fTraining BIT NOT NULL,
        ///	strInbox VARCHAR(100) NOT NULL,
        ///	strSpam VARCHAR(100) NOT NULL,
        ///	strUnsure VARCHAR(100) NOT NULL,
        ///	cSpam INT NOT NULL,
        ///	cHam INT NOT NULL,
        ///	nSpamCutoff REAL NOT NULL,
        ///	nHamCutoff REAL NOT NULL
        ///)
        ///
        ////*
        ///CREATE TABLE t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DatabaseScript {
            get {
                return ResourceManager.GetString("DatabaseScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE tblTokens
        ///WHERE id not IN (
        ///	SELECT idToken
        ///	FROM tblTokenCounts
        ///)
        ///
        ///DBCC DBREINDEX(tblTokens, &apos;&apos;, 100)
        ///
        ///DBCC DBREINDEX(tblTokenCounts, &apos;&apos;, 90)
        ///
        ///DBCC DBREINDEX(tblMessages, &apos;&apos;, 100)
        ///
        ///DBCC SHRINKDATABASE(ImapBayes).
        /// </summary>
        internal static string TrimScript {
            get {
                return ResourceManager.GetString("TrimScript", resourceCulture);
            }
        }
    }
}
